//request.rest
### 1. Contoh : Endpoint API : GET '/'
GET http://localhost:3000/

### 1a. Fungsi tes untuk register POST /api/users >> VALID
POST http://localhost:3000/api/users
Content-Type: application/json

{
"username": "test",
"password": "rahasia",
"name": "test"
}


### 1b. Fungsi tes untuk register >> ERROR Validation
POST http://localhost:3000/api/users
Content-Type: application/json

{
"username": "",
"password": "",
"name": ""
}


### 1c. Fungsi tes untuk register >> ERROR Duplicate 
POST http://localhost:3000/api/users
Content-Type: application/json

{
"username": "test",
"password": "rahasia",
"name": "test"
}

### 2a. Fungsi tes untuk login >> ERROR Validation
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
"username": "",
"password": ""
}

### 2b. Fungsi tes untuk login >> Valid
POST http://localhost:3000/api/users/login
Content-Type: application/json

{ 
"username": "test",
"password": "rahasia"
}

### 2c. Fungsi tes untuk login >> Password salah, User Benar
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
"username": "test",
"password": "salah"
}

### 2d. Fungsi tes untuk login >> Password salah, User Salah
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
"username": "test",
"password": "salah"
}

### 3a. Fungsi tes untuk GET USER >> ERROR Validation
GET http://localhost:3000/api/users/current
Content-Type: application/json
Authorization:  

{
"username": "test",
"password": "rahasia"
}

### 3b. Fungsi tes untuk GET USER >> Valid
### REGISTER
POST http://localhost:3000/api/users
Content-Type: application/json

{
"username": "test",
"password": "rahasia",
"name": "test"
}


### LOGIN >> token
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
"username": "test",
"password": "salah"
}

### GET dengan token
GET http://localhost:3000/api/users/current
Content-Type: application/json
Authorization: d6b46fdb-4063-4a4e-abd5-59738abc417a

{ 
"username": "",
"password": ""
}

### 4a. Fungsi tes untuk PATCH USER name password>> VALID
### REGISTER
POST http://localhost:3000/api/users
Content-Type: application/json

{
"username": "test",
"password": "rahasia",
"name": "test"
}


### LOGIN >> token
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
"username": "test",
"password": "rahasia"
}

### PATCH
PATCH http://localhost:3000/api/users/current
Content-Type: application/json
Authorization: 24f95c56-ec36-4773-bab3-b447e0be572c 

{
"name": "Edy",
"password": "rahasialagi"
}

### 4b. Fungsi tes untuk PATCH USER name >> VALID
PATCH http://localhost:3000/api/users/current
Content-Type: application/json
Authorization: 24f95c56-ec36-4773-bab3-b447e0be572c 

{
"name": "Edy Lagi"
}

### 4c. Fungsi tes untuk PATCH USER name >> VALID
PATCH http://localhost:3000/api/users/current
Content-Type: application/json
Authorization: 24f95c56-ec36-4773-bab3-b447e0be572c 

{
"password": "rahasialagi"
}

### 4c. Fungsi tes untuk PATCH USER name >> INVALID
PATCH http://localhost:3000/api/users/current
Content-Type: application/json
Authorization: salah 

### 5a. Fungsi tes untuk DELETE USER name password>> VALID
### REGISTER 
POST http://localhost:3000/api/users
Content-Type: application/json

{
"username": "test",
"password": "rahasia",
"name": "test"
}


### LOGIN >> token
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
"username": "test",
"password": "rahasia"
}

### LOGOUT
DELETE http://localhost:3000/api/users/logout
Content-Type: application/json
Authorization: e20cc8b8-212e-44b5-b8b0-c370d0bac357 

{
"username": "test"
}

### 5b. Fungsi tes untuk PATCH USER name >> VALID 
DELETE http://localhost:3000/api/users/logout
Content-Type: application/json
Authorization: salah

{
"username": "test"
}

### 1a. Fungsi tes untuk POST Contoh>> VALID
POST http://localhost:3000/api/contoh/public
Content-Type: application/json

{
"username": "edy"
}

### 1b. Fungsi tes untuk POST Contoh >> INVALID
POST http://localhost:3000/api/contoh/public
Content-Type: application/json

{
"username": "test"
}

